Mesd\ManyToManyBundle\Entity\Thing:
    type: entity
    table: null
    repositoryClass: Mesd\ManyToManyBundle\Entity\ThingRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
