parameters:
#    mesd_many_to_many.example.class: Mesd\ManyToManyBundle\Example

services:
#    mesd_many_to_many.example:
#        class: %mesd_many_to_many.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
